### ISSUE TITLE
Update column parsing for new Jmeter output

### ISSUE THREAD

**Issue by grosscol** [fcrepo4-labs/fcrepo_perf_analysis#15]
Jmeter output no longer produces 12 columns of output.
Update ingest script to handle the current output from Jmeter.
Update ingest script to handle legacy (12 column jmeter output).

**Comment by yinlinchen** [comment]
@grosscol I just want to let you know that I use JMeter Version 3.1 and the scripts are working fine with the JMeter output

**Comment by grosscol** [comment]
@yinlinchen Acknowledged.  I was never able to replicate the reported incompatibility.  My assumption was that it was an older version producing 12 columns, but that did not appear to be the case.
