### ISSUE TITLE
Upload test results to Amazon S3

### ISSUE THREAD

**Issue by awoods** [fcrepo4-labs/fcrepo_perf_analysis#5]
In order to facilitate the use of test results to generate performance graphs, the result files should be uploaded to and available from Amazon S3.
See: 
https://wiki.duraspace.org/display/FF/Test+1+Results+Summary
https://wiki.duraspace.org/display/FF/Test+2+Results+Summary
https://wiki.duraspace.org/display/FF/Test+3+Results+Summary
https://wiki.duraspace.org/display/FF/Test+4+Results+Summary
https://wiki.duraspace.org/display/FF/Test+5+Results+Summary

**Comment by awoods** [comment]
[Contents of the S3 Bucket](https://s3.amazonaws.com/f4-performance-results/notes.txt)
----------------------------------
### Test 1
https://wiki.duraspace.org/display/FF/Virginia+Tech+Results+-+Test+1
* [test1.vt.a.leveldb.tar.gz](https://s3.amazonaws.com/f4-performance-results/test1.vt.a.leveldb.tar.gz) 

https://wiki.duraspace.org/display/FF/Virginia+Tech+Results+-+Test+1+-+2nd
* [test1.vt.b.leveldb.tar](https://s3.amazonaws.com/f4-performance-results/test1.vt.b.leveldb.tar)

### Test 2
https://wiki.duraspace.org/display/FF/Virginia+Tech+Results+-+Test+2
* [test2.vt.leveldb.tar.gz](https://s3.amazonaws.com/f4-performance-results/test2.vt.leveldb.tar.gz)
* [test2.vt.mysql.tar.gz](https://s3.amazonaws.com/f4-performance-results/test2.vt.mysql.tar.gz)
* [test2.vt.pqsl.tar.gz](https://s3.amazonaws.com/f4-performance-results/test2.vt.pqsl.tar.gz)

https://wiki.duraspace.org/display/FF/Princeton+Results+-+Test+2
* [test2.pu.leveldb.tar](https://s3.amazonaws.com/f4-performance-results/test2.pu.leveldb.tar)
* [test2.pu.postgres.tar](https://s3.amazonaws.com/f4-performance-results/test2.pu.postgres.tar)
* [test2.pu.postgres-gc1.tar](https://s3.amazonaws.com/f4-performance-results/test2.pu.postgres-gc1.tar)
* [test2.pu.postgres-mode5.tar](https://s3.amazonaws.com/f4-performance-results/test2.pu.postgres-mode5.tar)

### Test 3
https://wiki.duraspace.org/display/FF/Princeton+Results+-+Test+3
* [test3.pu.postgres-mode5.tar](https://s3.amazonaws.com/f4-performance-results/test3.pu.postgres-mode5.tar)

https://wiki.duraspace.org/display/FF/Virginia+Tech+Results+-+Test+3
* [test3.vt.leveldb.tar.gz](https://s3.amazonaws.com/f4-performance-results/test3.vt.leveldb.tar.gz)
* [test3.vt.mysql.tar.gz](https://s3.amazonaws.com/f4-performance-results/test3.vt.mysql.tar.gz)
* [test3.vt.pqsl.tar.gz](https://s3.amazonaws.com/f4-performance-results/test3.vt.pqsl.tar.gz)

### Test 4
https://wiki.duraspace.org/display/FF/Princeton+Results+-+Test+4
* [test4.pu.leveldb.tar.gz](https://s3.amazonaws.com/f4-performance-results/test4.pu.leveldb.tar.gz)
* [test4.pu.postgres.tar.gz](https://s3.amazonaws.com/f4-performance-results/test4.pu.postgres.tar.gz)
* [test4.pu.postgres-mode5.tar.gz](https://s3.amazonaws.com/f4-performance-results/test4.pu.postgres-mode5.tar.gz)
* [test4.pu.postgres-mode51.tar.gz](https://s3.amazonaws.com/f4-performance-results/test4.pu.postgres-mode51.tar.gz)

https://wiki.duraspace.org/display/FF/Virginia+Tech+Results+-+Test+4
* [test4.vt.leveldb.tar.gz](https://s3.amazonaws.com/f4-performance-results/test4.vt.leveldb.tar.gz)

https://wiki.duraspace.org/display/FF/York+University+Results+-+Test+4
* [test4.yu.leveldb.tar.gz](https://s3.amazonaws.com/f4-performance-results/test4.yu.leveldb.tar.gz)

### Test 5
https://wiki.duraspace.org/display/FF/Virginia+Tech+Results+-+Test+5
* [test5.vt.leveldb.tar.gz](https://s3.amazonaws.com/f4-performance-results/test5.vt.leveldb.tar.gz)
* [test5.vt.mysql.tar.gz](https://s3.amazonaws.com/f4-performance-results/test5.vt.mysql.tar.gz)
* [test5.vt.pqsl.tar.gz](https://s3.amazonaws.com/f4-performance-results/test5.vt.pqsl.tar.gz)

https://wiki.duraspace.org/display/FF/Princeton+Results+-+Test+5
* [test5.pu.postgres-mode5.tar.gz](https://s3.amazonaws.com/f4-performance-results/test5.pu.postgres-mode5.tar.gz)

**Comment by awoods** [comment]
@grosscol ^^

**Comment by yinlinchen** [comment]
Should this page put in the wiki or under a folder in the repo?

**Comment by grosscol** [comment]
I'll add it to the Readme when I update the usage.
